version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

#  postgres:
#    image: postgres
#    container_name: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin123
#      POSTGRES_DB: cos40005
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - app-network

#  rabbitmq:
#    image: rabbitmq
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"  # For RabbitMQ management interface
#    networks:
#      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kib01
    ports:
      - "5601:5601"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es01
    ports:
      - "9200:9200"

  elastic2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es02
    ports:
      - "9201:9201"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
