# Generated by Django 5.0.6 on 2024-06-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos40005', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='address_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='area_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='area_classname_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='bedroom_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='bedroom_classname_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='description_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='pagination',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='price_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='publish_date_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='publish_date_classname_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='title_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='toilet_classname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='toilet_classname_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caches', to='cos40005.domain')),
            ],
        ),
    ]
