# Generated by Django 5.0.6 on 2024-11-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos40005', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Data Export',
                'verbose_name_plural': 'Data Exports',
            },
        ),
        migrations.CreateModel(
            name='ExtractedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('address', models.CharField(blank=True, max_length=2048, null=True)),
                ('price', models.CharField(max_length=2048)),
                ('area', models.CharField(blank=True, max_length=2048, null=True)),
                ('floor', models.CharField(blank=True, max_length=2048, null=True)),
                ('bedroom', models.CharField(blank=True, max_length=2048, null=True)),
                ('toilet', models.CharField(blank=True, max_length=2048, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=2048, null=True)),
                ('contact', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_properties', to='cos40005.domain')),
            ],
        ),
    ]
