# Generated by Django 5.0.6 on 2024-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos40005', '0002_domain_address_classname_domain_area_classname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='area_classname',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='area_classname_index',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='bedroom_classname',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='bedroom_classname_index',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='publish_date_classname',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='publish_date_classname_index',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='toilet_classname',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='toilet_classname_index',
        ),
        migrations.AddField(
            model_name='domain',
            name='area_xpath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='bedroom_xpath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='publish_date_xpath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='toilet_xpath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cache',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
